using System.Collections;
using UnityEngine;

public class IceCreamESkill : MonoBehaviour
{
    [Header("Ice Cream E")]
    [SerializeField] private float iceCreamEDuration = 3f;

    private bool isIceCreamEActive = false;

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.E) && !isIceCreamEActive)
        {
            StartCoroutine(E());
        }
    }

    IEnumerator E()
    {
        isIceCreamEActive = true;

        //Èú
        //ŒÓ””°šŒÒ
        Debug.Log("Èú, ŒÓ””°šŒÒ");

        float t = 0f;
        while (t < iceCreamEDuration)
        {
            t = Mathf.MoveTowards(t, iceCreamEDuration, Time.deltaTime);
            //Ă”Ă”Èś ŒÓ””Èžșč
            Debug.Log("Ă”Ă”Èś ŒÓ””Èžșč, ŒÓ””: " + t / iceCreamEDuration);
            yield return null;
        }
        isIceCreamEActive = false;
    }
}
